### PR TITLE
Added triceratop to registry.json

### PR DESCRIPTION
**Pull request by NicholasACTran**
In order to be eligible, you must complete the following:

- [x] I have included my module name

- [x] I have published my module to Nest.land

- [x] I have published my module to Deno.land

- [x] I have included my name (first and/or last)

- [x] I have included my GitHub username

- [x] I have created an Arweave Wallet and included my wallet address

 - [x] I confirm that this is my work and my module is not malicious

### CODE REVIEW

**Comment by NicholasACTran** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Comment by NicholasACTran** [comment]
recheckcla

**Comment by NicholasACTran** [comment]
> **CLA Assistant Lite bot:**
> Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> You can retrigger this bot by commenting **recheckcla** in this Pull Request

**Comment by maximousblk** [comment]
@NicholasACTran you need to make a comment with just the following text. no markdown formatting.

> I have read the CLA Document and I hereby sign the CLA

**Comment by maximousblk** [comment]
@NicholasACTran you need to make a comment with only the following text. (no markdown formatting)

> I have read the CLA Document and I hereby sign the CLA

**Comment by NicholasACTran** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
