### PR TITLE
Add maze_generator, terminal_images and a dmm PR

### PR DESCRIPTION
**Pull request by mjrlowe**

### CODE REVIEW

**Comment by TheWizardBear** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by mjrlowe** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by t8 — CHANGES_REQUESTED** [review]
Really appreciate this PR, but in order for it to work with the site, the module names will need to be formatted like so:

```js
{
  "nestdotland": "name" // without the https://nest.land
  "denoland": "name" // without the https://deno.land
}
```

**Comment by t8** [comment]
Thanks for catching this bug on our end

**Comment by mjrlowe** [comment]
Sorry, that should be fixed now.

**Comment by maximousblk** [comment]
sorry for the merge conflicts. it should be fixed now

**Comment by maximousblk** [comment]
if you could fill the above form i can merge this pr

**Comment by mjrlowe** [comment]
* [x]  I have included my module name
   * [x]  I have published my module to Nest.land
   * [x]  I have published my module to Deno.land
   * [x]  I have included my name (first and/or last)
   * [x]  I have included my GitHub username
   * [x]  I have created an [Arweave Wallet](https://www.arweave.org/wallet) and included my wallet address
   * [x]  I confirm that this is my work and my module is **not** malicious> 
   * [x]  I am a member of the [Nest.land Discord](https://discord.gg/Swcy7Ws)
   * [x]  I am following [@nestdotland](https://twitter.com/nestdotland) on Twitter
   * [x]  I am following [@deno_land](https://twitter.com/deno_land) on Twitter
   * [ ]  I am following [@ArweaveTeam](https://twitter.com/ArweaveTeam) on Twitter
   * [ ]  I am following [@peer2peerE](https://twitter.com/Peer2peerE) on Twitter

**Pull request merged**
