### PR TITLE
add 2 modules from hackathon-sidn

### PR DESCRIPTION
**Pull request by nikolockenvitz**
We (@FischerRene, @christianmalek, @nikolockenvitz) created two modules as part of hacktoberfest2020.

### CODE REVIEW

**Comment by nikolockenvitz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by FischerRene** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by christianmalek** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nikolockenvitz** [comment]
Could you may find another way for next years hacktoberfest to collect all modules that contributed? If all people are editing one file, it's pretty obvious to run into merge conflicts. I fear that some might even need to merge master branch into theirs multiple times.
Maybe a yaml file could help to automatically merge so that no manual merging is required. But of course I would prefer a process where not everyone has to edit the same file.

**Comment by t8** [comment]
@nikolockenvitz totally agree with you there. Lesson learned! If we end up doing this again, it will definitely be different next time.

**Review by t8 — APPROVED** [review]

**Pull request merged**
