### PR TITLE
Update registry.json

### PR DESCRIPTION
**Pull request by michael-spengler**

### CODE REVIEW

**Comment by michael-spengler** [comment]
Ravi is also having some trouble with eggs cli regarding version mismatches --> neural_nets not yet published to nest.land due to this reason.

[ERR] /mod.ts did not match any file. There may be a typo in the path.

**Comment by maximousblk** [comment]
cc @oganexon

**Comment by SteelAlloy** [comment]
> Ravi is also having some trouble with eggs cli regarding version mismatches --> neural_nets not yet published to nest.land due to this reason.
> 
> [ERR] /mod.ts did not match any file. There may be a typo in the path.

The bug was fixed this afternoon, I'll release asap 🙂

**Review by t8 — APPROVED** [review]

**Comment by t8** [comment]
We can merge once it's published to Nest.land :) Sorry for the trouble, but glad to hear @oganexon came to the rescue!

**Comment by ravimashru** [comment]
@oganexon unfortunately, I get an error when trying to upgrade the cli 😢 

```
$ eggs upgrade
[CRIT] An unexpected error occurred: "Failed to upgrade to the latest CLI version!"
[INFO] Debug file created. (/Users/i322118/eggs-debug.log)
[INFO] If you think this is a bug, please open a bug report at https://github.com/nestdotland/eggs/issues/new/choose with the information provided in /Users/i322118/eggs-debug.log
[INFO] Visit https://docs.nest.land/eggs/ for documentation about this command.
```
Debug file created (doesn't have much info though): [eggs-debug.log](https://github.com/nestdotland/hacktoberfest-2020/files/5434064/eggs-debug.log)

---

When I try to install v0.3.0 explicitly, I get this:
```
$ deno install -Afq --unstable https://x.nest.land/eggs@0.3.0/eggs.ts
error: TS2345 [ERROR]: Argument of type '{ depth: number; colors: boolean; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'colors' does not exist in type 'InspectOptions'.
        msg += ` ${Deno.inspect(arg, { depth: 10, colors: true })}`;
                                                  ~~~~~~~~~~~~
    at https://o7iau3xliniwrem4zttnmjn6j62moznlggnsqus7bbxvdkxy2p7a.arweave.net/d9AKbutDUWiRnMzm1iW-T7THZasxmyhSXwhvUar40_4/src/utilities/log.ts:64:51

TS2345 [ERROR]: Argument of type '{ colors: boolean; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'colors' does not exist in type 'InspectOptions'.
      Deno.inspect(module, { colors: true })
                             ~~~~~~~~~~~~
    at https://o7iau3xliniwrem4zttnmjn6j62moznlggnsqus7bbxvdkxy2p7a.arweave.net/d9AKbutDUWiRnMzm1iW-T7THZasxmyhSXwhvUar40_4/src/commands/publish.ts:330:30

Found 2 errors.
```

**Comment by ravimashru** [comment]
@t8 The module is now published to nest.land: https://nest.land/package/neural_nets! 🚀

**Comment by SteelAlloy** [comment]
@ravimashru Thanks for your feedback

`[ERR] /mod.ts did not match any file. There may be a typo in the path.`

This issue was fixed in eggs@0.3.1 👍 

```
$ deno install -Afq --unstable https://x.nest.land/eggs@0.3.0/eggs.ts
error: TS2345 [ERROR]: Argument of type '{ depth: number; colors: boolean; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'colors' does not exist in type 'InspectOptions'.
        msg += ` ${Deno.inspect(arg, { depth: 10, colors: true })}`;
                                                  ~~~~~~~~~~~~
    at https://o7iau3xliniwrem4zttnmjn6j62moznlggnsqus7bbxvdkxy2p7a.arweave.net/d9AKbutDUWiRnMzm1iW-T7THZasxmyhSXwhvUar40_4/src/utilities/log.ts:64:51

TS2345 [ERROR]: Argument of type '{ colors: boolean; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'colors' does not exist in type 'InspectOptions'.
      Deno.inspect(module, { colors: true })
                             ~~~~~~~~~~~~
    at https://o7iau3xliniwrem4zttnmjn6j62moznlggnsqus7bbxvdkxy2p7a.arweave.net/d9AKbutDUWiRnMzm1iW-T7THZasxmyhSXwhvUar40_4/src/commands/publish.ts:330:30

Found 2 errors.
```

You are using Deno@1.4.2 but eggs@0.3.0 only work with Deno@1.4.6.

So sorry, we don't have too many solutions to check the version of Deno used before executing the command.

```
$ eggs upgrade
[CRIT] An unexpected error occurred: "Failed to upgrade to the latest CLI version!"
[INFO] Debug file created. (/Users/i322118/eggs-debug.log)
[INFO] If you think this is a bug, please open a bug report at https://github.com/nestdotland/eggs/issues/new/choose with the information provided in /Users/i322118/eggs-debug.log
[INFO] Visit https://docs.nest.land/eggs/ for documentation about this command.
```
This one is a bug, we renamed `mod.ts` to `eggs.ts` but the upgrade command was not updated accordingly

**Comment by t8** [comment]
Awesome @ravimashru!

**Pull request merged**
