### PR TITLE
Add btoo to triceratop contributors list

### PR DESCRIPTION
**Pull request by btoo**

### CODE REVIEW

**Comment by btoo** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Comment by btoo** [comment]
recheckcla

**Comment by maximousblk** [comment]
@btoo you need to make a comment with only the following text. (no markdown formatting)

> I have read the CLA Document and I hereby sign the CLA

**Comment by btoo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by btoo** [comment]
recheckcla

**Pull request merged**
